use-grammars = { only = ["rust", "json", "toml", "css", "lua", "bash"] }

[[language]]
name = "rust"
auto-format = false

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "json"
auto-format = true

[[language]]
name = "css"
auto-format = true

[[language]]
name = "html"
auto-format = true
