inherits = "catppuccin_mocha"
"ui.background" = {}

[palette]
rosewater = "{{colors.orange.default.hex}}"
pink = "{{colors.red.default.hex}}"
mauve = "{{colors.purple.default.hex}}"
red = "{{colors.red.default.hex}}"
maroon = "{{colors.red.default.hex}}"
peach = "{{colors.orange.default.hex}}"
yellow = "{{colors.yellow.default.hex}}"
green = "{{colors.tertiary.default.hex}}"
teal = "{{colors.green.default.hex}}"
sky = "{{colors.primary.default.hex}}"
sapphire = "{{colors.blue.default.hex}}"
blue = "{{colors.primary.default.hex}}"
lavender = "{{colors.primary.default.hex}}"
text = "{{colors.on_surface.default.hex}}"
subtext1 = "#cccccc"
subtext0 = "#bbbbbb"
overlay2 = "#aaaaaa"
overlay1 = "#999999"
overlay0 = "#888888"
surface2 = "#777777"
surface1 = "#666666"
surface0 = "#555555"
base = "{{colors.surface.default.hex}}"
mantle = "{{colors.surface.default.hex}}"
crust = "{{colors.surface.default.hex}}"
