inherits = "catppuccin_mocha"
"ui.background" = {}
"ui.linenr" = { fg = "{{colors.tertiary_fixed_dim.default.hex}}" }
"ui.linenr.selected" = { fg = "{{colors.primary_fixed.default.hex}}" }

"ui.selection" = { fg = "{{colors.on_primary_container.default.hex}}", bg = "{{colors.primary_container.default.hex}}", underline = {color = "{{colors.on_primary_fixed_variant.default.hex}}", style = "line" } }

"ui.virtual.inlay-hint" = { fg = "{{colors.on_surface_variant.default.hex}}", modifiers = ["italic"] }

"comment" = { fg = "{{colors.outline.default.hex}}", bg = "{{colors.surface_container_high.default.hex}}", modifiers = ["italic"] }

"ui.statusline.normal" = { fg = "{{ colors.primary.default.hex }}", bg = "rosewater", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "{{ colors.secondary.default.hex }}", bg = "green", modifiers = ["bold"]  }
"ui.statusline.select" = { fg = "{{ colors.tertiary.default.hex }}", bg = "lavender", modifiers = ["bold"]  }


[palette]
rosewater = "{{colors.orange.default.hex}}"
pink = "{{colors.red.default.hex}}"
mauve = "{{colors.purple.default.hex}}"
red = "{{colors.red.default.hex}}"
maroon = "{{colors.red.default.hex}}"
peach = "{{colors.orange.default.hex}}"
yellow = "{{colors.yellow.default.hex}}"
green = "{{colors.tertiary.default.hex}}"
teal = "{{colors.green.default.hex}}"
sky = "{{colors.primary.default.hex}}"
sapphire = "{{colors.blue.default.hex}}"
blue = "{{colors.primary.default.hex}}"
lavender = "{{colors.primary.default.hex}}"
text = "{{colors.on_surface.default.hex}}"

# subtext1 = "#cccccc"
# subtext0 = "#bbbbbb"
# overlay2 = "#aaaaaa"
overlay1 = "#999999"
overlay0 = "#888888"
surface2 = "#777777"
# surface1 = "#666666"
# surface0 = "#555555"

subtext1 = "{{colors.on_surface_variant.default.hex}}"
subtext0 = "{{colors.on_surface_variant.default.hex}}"
overlay2 = "{{colors.secondary.default.hex}}"
# overlay1 = "{{colors.on_secondary_container.default.hex}}"
# overlay0 = "{{colors.on_primary_container.default.hex}}"
# surface2 = "{{colors.tertiary_container.default.hex}}"
surface1 = "{{colors.primary_container.default.hex}}"
surface0 = "{{colors.surface_dim.default.hex}}"
base = "{{colors.surface.default.hex}}"
mantle = "{{colors.surface.default.hex}}"
crust = "{{colors.surface.default.hex}}"

cursorline = "{{colors.secondary_container.default.hex}}"
