palette = 'colors'
scan_timeout = 10
add_newline = false
format = " $directory$username$character"
right_format = "$cmd_duration$git_branch$git_metrics$git_commit$git_state$all"

[palettes.colors]
mustard = '#af8700' # example
color1 = '{{colors.primary_fixed_dim.default.hex}}'
color2 = '{{colors.on_primary.default.hex}}'
color3 = '{{colors.on_surface_variant.default.hex}}'
color4 = '{{colors.surface_container.default.hex}}'
color5 = '{{colors.on_primary.default.hex}}'
color6 = '{{colors.surface_dim.default.hex}}'
color7 = '{{colors.surface.default.hex}}'
color8 = '{{colors.primary.default.hex}}'
color9 = '{{colors.tertiary.default.hex}}'


[cmd_duration]
format = "[$duration](italic dimmed blue) "

[line_break]
disabled = true
[character]
success_symbol = "[λ](color9)"
error_symbol = "[λ](@{error})"
vimcmd_symbol = "[λ](green)"

[directory]
read_only = " ro"
home_symbol = "~"
style = "cyan"

[git_commit]
tag_symbol = " tag "

[git_branch]
format = "[$symbol](fg:color5)[(fg:color5) $branch(:$remote_branch)](fg:color3) "
symbol = ""

[git_metrics]
added_style = "bold yellow"
deleted_style = "bold red"
disabled = false

[git_status]
disabled = true

[time]
disabled = false
format = "[(fg:color5) $time](italic dimmed fg:color3) "
time_format = "%R"

[aws]
symbol = "aws "
[bun]
symbol = "bun "
[c]
symbol = "C "
[cobol]
symbol = "cobol "
[conda]
symbol = "conda "
[crystal]
symbol = "cr "
[cmake]
symbol = "cmake "
[daml]
symbol = "daml "
[dart]
symbol = "dart "
[deno]
symbol = "deno "
[dotnet]
symbol = " NET "
[docker_context]
symbol = "docker "
[elixir]
symbol = "exs "
[elm]
symbol = "elm "
[golang]
symbol = "go "
[guix_shell]
symbol = "guix "
[hg_branch]
symbol = "hg "
[java]
symbol = "java "
[julia]
symbol = "jl "
[kotlin]
symbol = "kt "
[lua]
symbol = "lua "
[memory_usage]
symbol = "memory "
[meson]
symbol = "meson "
[nim]
symbol = "nim "
[nix_shell]
symbol = "nix "
[ocaml]
symbol = "ml "
[opa]
symbol = "opa "
[nodejs]
symbol = "nodejs "
[package]
symbol = "pkg "
[perl]
symbol = "pl "
[php]
symbol = "php "
[pulumi]
symbol = "pulumi "
[purescript]
symbol = "purs "
[python]
symbol = "py "
[raku]
symbol = "raku "
[ruby]
symbol = "rb "
[rust]
symbol = "rs "
[scala]
symbol = "scala "
[spack]
symbol = "spack "
[swift]
symbol = "swift "
[terraform]
symbol = "terraform "
[zig]
symbol = "zig "
