[manager]
prepend_keymap = [
  # goto
  { on = ["g", "c"], run = "cd ~/dotfiles" },
  { on = ["g", "C"], run = "cd ~/.config" },
  { on = ["g", "r"], run = "cd ~/repo" },
  { on = ["g", "p"], run = "cd ~/project" },
  { on = ["g", "n"], run = "cd ~/novel" },

  # FIX:edit file
  # { on = ["e", "c"], run = "shell 'open-file-in-helix-kitty.nu ~/dotfiles'" },
]
